sudo: required
services:
- docker
before_install:
- docker build -f Dockerfile-linux -t RdeWilde/electrum-ion-release:Linux .
- ./python-trezor-wine.sh
- ./python-x11_hash-wine.sh
- docker build -f Dockerfile-wine -t RdeWilde/electrum-ion-release:Wine .
script:
- git clone https://github.com/RdeWilde/electrum-ion.git
- docker run --rm -v $(pwd):/opt -w /opt/electrum-ion -t RdeWilde/electrum-ion-release:Linux /opt/build_linux.sh
- docker run --rm -v $(pwd):/opt -v $(pwd)/electrum-ion/:/root/.wine/drive_c/electrum -w /opt/electrum-ion -t RdeWilde/electrum-ion-release:Wine /opt/build_wine.sh
deploy:
  provider: releases
  api_key:
    secure: SQXk7lgMBhI8dlpE5+xj54Tl2VMS0t3TJpJnLEgm0SBeenX3S7vmMKBaWbA1qy8zA4h9LWBXxPgy4FKL+9qLOl5cnyJghwlWxoFplUvN2PcDwtnOKcRjvGawFktKhecXTZPwUFjG8AE32jJqY+Ps+1pEgg44qUI7EoWYcPMmItWYHjeMBFfF7+MdzfHxQR7DykFr3QmDnWaTf6T/ojLE3muHBvOI0fVzhFpb0Pd1uWaG1DNtUL2/ALNFbjLKPMjlNKaozgyxUcNxSyRtFjGDlWuqr89snMDIHexG7J3d/UQtfwFg7l55XpZ/UfHCB8NwR7m7n3QYPqaMnybDIFRp8hxwcBijLsWtXy1AHW4p08hxcbDoz2jU84DtRXI6cT3zrhQeWplwS0+dkRpt7CF5SpEIzDRtabbBC5geR4Q6GFdm97fab6gFwKGJbmfcX1DTRAmpuIA0kqHASAHqI9qY0Een3B0GyeO0Ix5CHjmgVZNwY6mfx3OrDaISb7mTiwYjgeo5FKkOTKcEKYSXU1FXB/yzarvistG+lowQ4VAq/alG6sqO/SoHnQyiEw/13LjTTciWYIarP88xFtGC7/Y81k6jo7jzpnJMLRp9P6YOaJ8U5/DDQOGC2GprbqkCIAkL9NOB2bb8E2D4eYDLB7FWhBjWKbRRx7JmPW+9x6viJ5Y=
  file:
    - electrum-ion/dist/electrum-ion-2.6.4.tar.gz
    - electrum-ion/dist/electrum-setup.exe
  on:
    repo: RdeWilde/electrum-ion-release
    all_branches: true